micronaut:
  application:
    name: pixKeyManagerGrpc

datasources:
  default:
    url: ${DB_URI:`jdbc:postgresql://localhost:5432/postgres`}
    driverClassName: org.postgresql.Driver
    username: ${POSTGRES_PASSWORD:postgres}
    password: ${POSTGRES_PASSWORD:pixkeypwd}
    schema-generate: CREATE_DROP
    dialect: ${DB_DIALECT:POSTGRES}
jpa.default.properties.hibernate.hbm2ddl.auto: update
jpa.default.properties.hibernate.show_sql: true
jpa.default.properties.hibernate.format-sql: true

#grpc:
#  server:
#    port: ${SERVER_PORT:50051}
#    keep-alive-time: 1h
#    max-inbound-message-size: 1024

itau.erp.url: ${ITAU_URL:`http://localhost:9091/api/v1`}